#### Question 1 - Load the car dataset into a Pandas DataFrame. Also, load all the DataFrame columns into specific variables as lists. Name your variables accordingly. - 5% marks

In [7]:
import pandas as pd
dataset=pd.read_csv("E:\Cars_group1.csv")

name = dataset['name'].tolist()
year = dataset['year'].tolist()
selling_price = dataset['selling_price'].tolist()
km_driven=dataset['km_driven'].tolist()
fuel=dataset['fuel'].tolist()
seller_type=dataset['seller_type'].tolist()
transmission=dataset['transmission'].tolist()
owner=dataset['owner'].tolist()
mileage=dataset['mileage(ppl)'].tolist()
engine=dataset['engine'].tolist()
max_power=dataset['max_power(bhp)'].tolist()
torque=dataset['torque'].tolist()
seats=dataset['seats'].tolist()
Make=dataset['Make'].tolist()
Model=dataset['Model'].tolist()






#### Question 2 - Write a program that counts and displays the number of cars with manual transmissions. - 10% marks

In [9]:
manual_count = (dataset['transmission'] == 'Manual').sum()
automatic_count=(dataset['transmission'] == 'Automatic').sum()
print(f"The number of cars with manual transmission is: {manual_count}")
print(f"The number of cars with Automatic transmission is: {automatic_count}")


The number of cars with manual transmission is: 871
The number of cars with Automatic transmission is: 129


#### Expected output:

The number of manual cars was: 871 and automatic was:129

#### Question 3 - Write a function that takes the car make (e.g., "Toyota") and returns the percentage of fuel types of that particular Make. - 10% marks

In [20]:
def fuelpercentage(car):
    new_data = dataset[dataset['car'] == make]
    fuel_percentage = new_data.groupby('Fuel').size() / new_data.shape[0] * 100
    return fuel_percentage

make = ''
result = fuel_percentage(make)
print(f"Fuel type percentages for {make}:\n{result}")
    

Fuel type percentages for Toyota:
Series([], Name: fuel, dtype: object)


#### Expected outputs:

Please enter the number of the car make:  Chevrolet
The number of cars produced by Chevrolet in this dataset was 22

#### Question 4 - Create a program to display the max, min and mean price per Owner. - 10 % marks

In [30]:
def display_owner(owners, selling_prices):
    stats_per_owner = dataset.groupby('Owner')['Selling_Price'].agg(['max', 'min', 'mean'])
    for owner, stats in stats_per_owner.iterrows():
        max_price = stats['max']
        min_price = stats['min']
        avg_price = stats['mean']
        output += f"The prices for {owner} Owner are the following, Max: {max_price}, Min: {min_price}, Avg: {avg_price}\n"
    return output

result = display_owner(owner, selling_price)
print(result)


KeyError: 'Owner'

#### Expected outputs:
The prices for Third Owner are the following, Max: 50000, Min: 50000, Avg: 50000.0
The prices for Second Owner are the following, Max: 160000, Min: 160000, Avg: 160000.0
The prices for First Owner are the following, Max: 695000, Min: 695000, Avg: 695000.0
The prices for Fourth & Above Owner are the following, Max: 450000, Min: 450000, Avg: 450000.0

#### Question 5 - Implement a function to find and print the model of the oldest car as well as its maker in the dataset. Consider the 'Year' list to determine the age and the "Model". - 10% marks.

In [29]:
def oldest_car_details(makers, models, years):
    oldest_car = years.index(min(years))
    oldest_car_maker = Make[oldest_car]
    oldest_car_model = Model[oldest_car]
    return oldest_car_maker, oldest_car_model

oldest_maker, oldest_model = oldest_car_details(Make,Model,year)
print(f"The oldest car from the  model '{oldest_model}' was produced by '{oldest_maker}'.")

The oldest car from the  model 'Willys' was produced by 'Mahindra'.


#### Expected output:
The oldest car from the model Willys was produced by Mahindra

#### Question 6 - Create a loop that categorizes cars into three age groups: 'New,' 'Used,' and 'Vintage.' The groups should be based on the manufacture year (e.g., 'New' for cars less than 5 years old, 'Used' for cars between 5 and 20 years old, and 'Vintage' for cars over 20 years old). Use the Loop to create a list containing these values and create another repetition structure to print the Make, model, year, price and km driven of Vintage cars. - 20% marks.

In [49]:
age_group = []
for y in year:
    car_age = 2020 - y
    if car_age < 5:
        age_group.append('New')
    elif 5 <= car_age <= 20:
        age_group.append('Used')
    else:
        age_group.append('Vintage')

print("Information about Vintage cars:")
index=0
while index < len(age_group):
    if age_group[index] == 'Vintage':
        print(f"Make: {Make[index]}, Model: {Model[index]}, Year: {year[index]}, Price: {selling_price[index]}, Km Driven: {km_driven[index]}")
        
    index += 1

Information about Vintage cars:
Make: Maruti, Model: 800, Year: 1997, Price: 50000, Km Driven: 120000
Make: Maruti, Model: 800, Year: 1997, Price: 50000, Km Driven: 60000
Make: Mahindra, Model: Jeep, Year: 1996, Price: 163000, Km Driven: 5000
Make: Peugeot, Model: 309, Year: 1997, Price: 57000, Km Driven: 110000
Make: Maruti, Model: 800, Year: 1997, Price: 50000, Km Driven: 110000
Make: Mahindra, Model: Willys, Year: 1983, Price: 300000, Km Driven: 10000
Make: Maruti, Model: 800, Year: 1996, Price: 40000, Km Driven: 32000


#### Expected output of the first element of the loop:

Make: Maruti, Model: 800, Year: 1997, Price: 50000, Km Driven: 120000

#### Question 7 - Create a function that calculates the average km_driven for all cars built between the years 2010 and 2020 and print it. You should provide the user with the option to enter it's own range of years (between 2010 to 2020). Use the full dataset and Numpy to answer this question. - 20% marks.

In [62]:
def average_km_range(year_start, year_end, years, km_driven):
    km_in_range = []
    for i in range(len(years)):
        if (year_start <= years[i]) and (years[i] <= year_end):
            km_in_range.append(km_driven[i])
    if km_in_range:
        average_km = sum(km_in_range) / len(km_in_range)
        return average_km
    else:
        return "No cars found in the specified year range."



start_year = int(input("Enter start year (between 2010 to 2020): "))
end_year = int(input("Enter end year (between 2010 to 2020): "))

if (2010 <= start_year <= 2020) and (2010 <= end_year <= 2020) and (start_year <= end_year):
    result = average_km_range(start_year, end_year, year, km_driven)
    print(f"Average mileage for {start_year} and {end_year}: {result}")
else:
    print("Please enter a valid range of years between 2010 to 2020.")

Enter start year (between 2010 to 2020):  2010
Enter end year (between 2010 to 2020):  2018


Average km driven between 2010 and 2018: 70015.15482233503


#### Expected output:
The Average mileage for the range was 65304.28 km.

#### Question 8 - write a function that will accept an integer as input (validate the input using the Try-except structure). - 15% marks.

In [66]:
def print_pattern(size):
    try:
        if size <= 0:
            raise ValueError("Please enter a positive integer.")

        for i in range(1, size + 1):
            print(' ' * (size - i), end='')
            print(str(i) * i, end='')
            print(' ' * ((size - i) * 2), end='')
            print(str(size - i + 1) * (size - i + 1))

    except ValueError as e:
        print(f"Invalid input: {e}")

try:
    user_input = int(input("Enter an integer: "))
    print_pattern(user_input)
except ValueError:
    print("Invalid input. Please enter an integer.")


Enter an integer:  4


   1      4444
  22    333
 333  22
44441


#### Expected output:

<img src="group1_8.jpeg" width="80">